### ISSUE TITLE
Missing AVRecorder.png

### ISSUE THREAD

**Issue by GearTheWorld** [Sunhick/ScreenRecorder#2]
There's a reference to Images/AVRecorder.png which isn't found by the project when running it.

![2016-10-06 07_14_22-films tv](https://cloud.githubusercontent.com/assets/8614008/19150392/94aaf130-8b94-11e6-8bed-70a02d9531c1.png)

**Comment by GearTheWorld** [comment]
Also once the capture is completed, trying to view the mp4 results in nothing.  Nothing shows, I tried with multiple video player without any luck

**Comment by Sunhick** [comment]
did you the run the WPF application or the Winforms app ? Winforms app is old and I'm not working on it. I tried WPF app this morning. It works fine. By default the the video gets encoded in MKV format. try opening in the VLC player. Also compile the WPF code in x64 mode and set CAM.Starter as startup project. Thanks for the pointing the missing file. I updated it.

**Comment by Sunhick** [comment]
I have also updated the new binaries. unzip and run CAM.starter.exe.
